name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "hello world"

  job-2:
    runs-on: ubuntu-latest
    needs: my-job   
    steps:
      - name: dependent-step
        run: echo "run-2"
